# Generated by Django 4.0.5 on 2022-06-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='verified_fich',
            new_name='verified_finch',
        ),
    ]
