# Generated by Django 4.0.5 on 2022-06-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('finches', models.ManyToManyField(to='main_app.finch')),
            ],
        ),
    ]
