# Generated by Django 4.0.5 on 2022-06-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_verified_fich_finch_verified_finch'),
        ('main_app', '0005_finch_user_alter_finch_age'),
    ]

    operations = [
    ]
